export const route = {
  // home as new chat or thread
  home: '/',
  the_agent: '/the-agent',
  appLogs: '/logs',
  project: '/project',
  projectDetail: '/project/$projectId',
  commands: '/commands',
  settings: {
    index: '/settings',
    model_providers: '/settings/providers',
    providers: '/settings/providers/$providerName',
    general: '/settings/general',
    attachments: '/settings/attachments',
    interface: '/settings/interface',
    privacy: '/settings/privacy',
    shortcuts: '/settings/shortcuts',
    extensions: '/settings/extensions',
    database: '/settings/database',
    local_api_server: '/settings/local-api-server',
    mcp_servers: '/settings/mcp-servers',
    https_proxy: '/settings/https-proxy',
    hardware: '/settings/hardware',
    assistant: '/settings/assistant',
  },
  hub: {
    index: '/hub/',
    model: '/hub/$modelId',
  },
  localApiServerlogs: '/local-api-server/logs',
  systemMonitor: '/system-monitor',
  threadsDetail: '/threads/$threadId',
  database: '/database',
}
